development:
  adapter: postgresql
  encoding: unicode
  database: mule_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: mule_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: mule_production
  pool: 5
  timeout: 5000