development:
  adapter: postgresql
  encoding: unicode
  database: mule_development

test:
  adapter: postgresql
  encoding: unicode
  database: mule_test

production:
  adapter: postgresql
  encoding: unicode
  database: mule_production